server:
  port: 8080

spring:
  application:
    name: sm-gateway

zuul:
  routes:
    catalog:
      path: /catalog/**
      url: http://localhost:8081
      strip-prefix: true
      sensitive-headers:
    core:
      path: /**
      url: http://localhost:8081
      sensitive-headers:
  ignored-patterns: /routes/**